Quiz-Application.Web/Controllers/ExamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Quiz_Application.Web.Authentication;
using Quiz_Application.Services.Entities;
using Quiz_Application.Web.Models;
using Quiz_Application.Services.Repository.Interfaces;
using Quiz_Application.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
using Quiz_Application.Web.Extensions;

namespace Quiz_Application.Web.Controllers
{    
    [BasicAuthentication]   
    public class ExamController : Controller
    {
        private readonly QuizDBContext _context;
        private readonly ILogger<ExamController> _logger;
        private readonly IExam<Services.Entities.Exam> _exam;
        private readonly IQuestion<Services.Entities.Question> _question;
        private readonly IResult<Services.Entities.Result> _result;
        public ExamController(ILogger<ExamController> logger, IExam<Services.Entities.Exam> exam, IQuestion<Services.Entities.Question> question, IResult<Services.Entities.Result> result, QuizDBContext context)
        {
            _context = context;
            _logger = logger;
            _exam = exam;
            _question = question;
            _result = result;
        }
             
        [HttpGet]
        [Route("~/api/Exams")]
        public async Task<IActionResult> Exams()
        {           
            try
            {
                IEnumerable<Exam> lst = await _exam.GetExamList();               
                return Ok(lst.ToList());
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message, ex.InnerException);
            }
            finally 
            {
            }
        }

        [HttpGet]
        [Route("~/api/Exam/{ExamID?}")]
        public async Task<IActionResult> Exam(int ExamID)
        {
            try
            {
                Exam exm = await _exam.GetExam(ExamID);
                return Ok(exm);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message, ex.InnerException);
            }
            finally 
            {
            }
        }

        // GET: Exam/CreateExam
        public IActionResult CreateExam()
        {
            ViewBag.Candidate = HttpContext.Session.GetObjectFromJson<Candidate>("AuthenticatedUser");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateExam([Bind("ExamID,Name,FullMarks,Duration")] Exam exam)
        {
            ViewBag.Candidate = HttpContext.Session.GetObjectFromJson<Candidate>("AuthenticatedUser");
            if (ModelState.IsValid)
            {
                _context.Add(exam);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(CreateExam));
            }
            return View(exam);
        }

        public IActionResult CreateQuestion()
        {
            ViewBag.Candidate = HttpContext.Session.GetObjectFromJson<Candidate>("AuthenticatedUser");
            ViewBag.ExamID = new SelectList(_context.Exam, "ExamID", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateQuestion([Bind("ExamID,QuestionType,QuestionText,ChoiceOne,ChoiceTwo,ChoiceThree,ChoiceFour,ChoiceNo")] CreateQuestionViewModel model)
        {
            ViewBag.Candidate = HttpContext.Session.GetObjectFromJson<Candidate>("AuthenticatedUser");
            if (ModelState.IsValid)
            {
                Question question = new Question()
                {
                    ExamID = model.ExamID,
                    QuestionType = model.QuestionType,
                    DisplayText = model.QuestionText,
                };
                _context.Add(question);
                await _context.SaveChangesAsync();
                Choice choiceOne = new Choice()
                {
                    QuestionID = question.QuestionID,
                    DisplayText = model.ChoiceOne
                };
                Choice choiceTwo = new Choice()
                {
                    QuestionID = question.QuestionID,
                    DisplayText = model.ChoiceTwo
                };
                Choice choiceThree = new Choice()
                {
                    QuestionID = question.QuestionID,
                    DisplayText = model.ChoiceThree
                };
                Choice choiceFour = new Choice()
                {
                    QuestionID = question.QuestionID,
                    DisplayText = model.ChoiceFour
                };
                _context.Add(choiceOne);
                _context.Add(choiceTwo);
                _context.Add(choiceThree);
                _context.Add(choiceFour);
                await _context.SaveChangesAsync();
                Choice answerChoice;
                switch (model.ChoiceNo)
                {
                    case 1:
                        answerChoice = choiceOne;
                        break;
                    case 2:
                        answerChoice = choiceTwo;
                        break;
                    case 3:
                        answerChoice = choiceThree;
                        break;
                    case 4:
                        answerChoice = choiceFour;
                        break;
                    default:
                        answerChoice = choiceOne;
                        break;
                }
                Answer answer = new Answer()
                {
                    QuestionID = question.QuestionID,
                    ChoiceID = answerChoice.ChoiceID,
                    DisplayText = answerChoice.DisplayText
                };
                _context.Add(answer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(CreateQuestion));
            }
            return View(model);
        }

        public IActionResult CreateChoice()
        {
            ViewBag.Candidate = HttpContext.Session.GetObjectFromJson<Candidate>("AuthenticatedUser");
            ViewBag.QuestionID = new SelectList(_context.Question, "QuestionID", "DisplayText");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateChoice([Bind("ChoiceID,QuestionID,DisplayText")] Choice choice)
        {
            ViewBag.Candidate = HttpContext.Session.GetObjectFromJson<Candidate>("AuthenticatedUser");
            if (ModelState.IsValid)
            {
                _context.Add(choice);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(CreateChoice));
            }
            return View(choice);
        }

        public IActionResult CreateAnswer()
        {
            ViewBag.Candidate = HttpContext.Session.GetObjectFromJson<Candidate>("AuthenticatedUser");
            ViewBag.QuestionID = new SelectList(_context.Question, "QuestionID", "DisplayText");
            ViewBag.ChoiceID = new SelectList(_context.Choice, "ChoiceID", "DisplayText");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateAnswer([Bind("Sl_No,QuestionID,ChoiceID,DisplayText")] Answer answer)
        {
            ViewBag.Candidate = HttpContext.Session.GetObjectFromJson<Candidate>("AuthenticatedUser");
            if (ModelState.IsValid)
            {
                _context.Add(answer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(CreateAnswer));
            }
            return View(answer);
        }

       

        [HttpGet]
        [Route("~/api/Questions/{ExamID?}")]
        public async Task<IActionResult> Questions(int ExamID)
        {
            try
            {
                QnA _obj = await _question.GetQuestionList(ExamID);
                _obj.RandomOrder(_obj.questions);
                return Ok(_obj);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message, ex.InnerException);
            }
            finally 
            {
            }
        }

        [HttpPost]
        [Route("~/api/Score")]       
        public async Task<IActionResult> Score(List<Option> objRequest)
        {
            int i = 0;
            bool IsCorrect = false;
            List<Result> objList = null;
            string _SessionID = null;
            try
            {               
                if (objRequest.Count > 0)
                {
                    _SessionID = Guid.NewGuid().ToString() + "-" + DateTime.Now;
                    objList = new List<Result>();
                    foreach (var item in objRequest)
                    {
                        if (item.AnswerID == item.SelectedOption)
                            IsCorrect = true;
                        else
                            IsCorrect = false;

                        Result obj = new Result()
                        {
                            CandidateID = item.CandidateID,
                            ExamID = item.ExamID,
                            QuestionID = item.QuestionID,
                            AnswerID = item.AnswerID,
                            SelectedOptionID = item.SelectedOption,
                            IsCorrent = IsCorrect,
                            SessionID= _SessionID,
                            CreatedBy = "SYSTEM",
                            CreatedOn = DateTime.Now
                        };
                        objList.Add(obj);
                    }
                    i = await _result.AddResult(objList);
                }
               
            }
            catch (Exception ex)
            {

Quiz-Application.Web/Controllers/ScoreController.cs
using System.IO;
using System.Net;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using DinkToPdf.Contracts;
using DinkToPdf;
using Quiz_Application.Web.Extensions;
using Quiz_Application.Web.Authentication;
using Quiz_Application.Services.Entities;
using Quiz_Application.Services.Repository.Interfaces;

namespace Quiz_Application.Web.Controllers
{
    [BasicAuthentication]
    public class ScoreController : Controller
    {
       private readonly IConverter _converter;
       private readonly ILogger<ScoreController> _logger;
       private readonly IResult<Services.Entities.Result> _result;

       public ScoreController(ILogger<ScoreController> logger, IResult<Services.Entities.Result> result, IConverter converter)
       {
            _logger = logger;
            _result = result;
            _converter = converter;
       }

       public async Task<IActionResult> Result()
       {
            ViewBag.Candidate = HttpContext.Session.GetObjectFromJson<Candidate>("AuthenticatedUser");
            try
            {
                Candidate _objCandidate = HttpContext.Session.GetObjectFromJson<Candidate>("AuthenticatedUser");

                IEnumerable<QuizAttempt> _obj = await _result.GetAttemptHistory(_objCandidate.Candidate_ID);
                Root objRoot = new Root(){
                    objCandidate= _objCandidate,
                    objAttempt = _obj.ToList() 
                };               
                return View(objRoot);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message, ex.InnerException);
            }
            finally 
            {
            }
        }

        [HttpPost]
        [Route("~/api/Report")]
        public async Task<IActionResult> Report(ReqReport argRpt)
        {
            try
            {
                IEnumerable<QuizReport> lst = await _result.ScoreReport(argRpt);
                return Ok(lst.ToList());
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message, ex.InnerException);
            }
            finally
            {
            }
        }

        [HttpPost]
        [Route("~/api/CreatePDF")]
        public async Task<IActionResult> CreatePDF(ReqCertificate argPDFRpt)
        {
            ResPDF obj = null;
            try
            {                
                string html = await _result.GetCertificateString(argPDFRpt);
                string UploadFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "UploadedFiles/Report");
                string UniqueFileName = argPDFRpt.CandidateID + "_Certificate.pdf";
                string UploadPath = Path.Combine(UploadFolder, UniqueFileName);
                var globalSettings = new GlobalSettings
                {
                    ColorMode = ColorMode.Color,
                    Orientation = Orientation.Landscape,
                    PaperSize = PaperKind.A4,
                    Margins = new MarginSettings { Top = 10, Bottom = 10 },
                    Out = UploadPath
                };
                var objectSettings = new ObjectSettings
                {
                    PagesCount = true,
                    HtmlContent = html,
                    WebSettings = { DefaultEncoding = "utf-8" },
                };
                var htmlToPdfDocument = new HtmlToPdfDocument()
                {
                    GlobalSettings = globalSettings,
                    Objects = { objectSettings },
                };
                _converter.Convert(htmlToPdfDocument);
                obj = new ResPDF();
                obj.IsSuccess = true;
                obj.Path = "/UploadedFiles/Report/" + UniqueFileName;
            }
            catch (Exception ex)
            {
                obj.IsSuccess = false;
                obj.Path = null;
                throw new Exception(ex.Message, ex.InnerException);                 
            }
            finally
            {
            }
            return Json(obj);
        }
                
    }
}

Quiz-Application.Web/Views/Shared/_Layout.cshtml
@using Quiz_Application.Services.Entities
@using Quiz_Application.Services.Entities
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - Quiz_Application</title>
	<link rel="icon" type="image/png" href="~/images/icons/favicon.ico" />
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
	<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
	<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans'>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
	<style>
		2
		html, body, h1, h2, h3, h4, h5 {
			font-family: "Open Sans", sans-serif
		}
	</style>
</head>
<body class="w3-theme-l5">

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container-fluid">
			<a asp-controller="Home" asp-action="Index" class="navbar-brand"><i class="fa fa-home w3-margin-right"></i>EasyQuiz</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a asp-controller="Home" asp-action="Index" class="nav-link active" aria-current="page" title="News"><i class="fa fa-book"></i> Quiz</a>
					</li>
					@{
						Candidate candidate = ViewBag.Candidate;
					}
					@if (candidate.Roles == "Admin")
					{
						<li class="nav-item">
							<a asp-controller="Score" asp-action="Result" class="nav-link" title="Messages"><i class="fa fa-server"></i> Score Report</a>
						</li>
						<li class="nav-item">
                            <a asp-controller="Home" asp-action="Profile" class="nav-link">Edit Profile</a>
						</li>
						<li class="nav-item dropdown">
							<a class=" nav-link dropdown-toggle" id="navbarDropdown" style="cursor:pointer;" role="button" data-bs-toggle="dropdown">
								Create
							</a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li><a asp-controller="Exam" asp-action="CreateExam" class="dropdown-item">Exam</a></li>
                                <li><a asp-controller="Exam" asp-action="CreateQuestion" class="dropdown-item">Question</a></li>
                                <li><a asp-controller="Exam" asp-action="CreateChoice" class="dropdown-item">Choice</a></li>
                                <li><a asp-controller="Exam" asp-action="CreateAnswer" class="dropdown-item">Answer</a></li>
                            </ul>
						</li>
					}

				</ul>
			</div>
		</div>
	</nav>
	<!-- Navbar -->
	@*<div class="w3-top">
	<div class="w3-bar w3-theme-d2 w3-left-align w3-large">
	<a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-theme-d2" href="javascript:void(0);" onclick="openNav()"><i class="fa fa-bars"></i></a>
	<a class="w3-bar-item w3-button w3-padding-large w3-theme-d4"><i class="fa fa-home w3-margin-right"></i>EasyQuiz</a>
	<a asp-controller="Home" asp-action="Index" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="News"><i class="fa fa-book"></i> Quiz</a>
	@{
	Candidate candidate = ViewBag.Candidate;
	}
	@if (candidate.Roles == "Admin")
	{
	
	<div class="w3-dropdown-hover w3-hide-small">
	<button class="w3-button w3-padding-large" title="Notifications"><i class="fa fa-cog"></i> Settings</button>
	<div class="w3-dropdown-content w3-card-4 w3-bar-block" style="width:300px">
	<a asp-controller="Home" asp-action="Profile" class="w3-bar-item w3-button">Edit Profile</a>
	</div>
	<div class="w3-dropdown-content w3-card-4 w3-bar-block" style="width:300px">
	<a asp-controller="Home" asp-action="Profile" class="w3-bar-item w3-button">Create Exam</a>
	</div>
	<div class="w3-dropdown-content w3-card-4 w3-bar-block" style="width:300px">
	<a asp-controller="Home" asp-action="Profile" class="w3-bar-item w3-button">Create Question</a>
	</div>
	<div class="w3-dropdown-content w3-card-4 w3-bar-block" style="width:300px">
	<a asp-controller="Home" asp-action="Profile" class="w3-bar-item w3-button">Create Choice</a>
	</div>
	<div class="w3-dropdown-content w3-card-4 w3-bar-block" style="width:300px"><a asp-controller="Score" asp-action="Result" class="w3-bar-item w3-button w3-hide-small w3-padding-large w3-hover-white" title="Messages"><i class="fa fa-server"></i> Score Report</a>
	<a asp-controller="Home" asp-action="Profile" class="w3-bar-item w3-button">Create Answer</a>
	</div>
	</div>
	}
	<a asp-action="Logout" asp-controller="Account" class="w3-bar-item w3-button w3-hide-small w3-right w3-padding-large w3-hover-white" title="Sign out">
	<img src="https://www.w3schools.com/w3images/avatar2.png" class="w3-circle" style="height:23px;width:23px" alt="Avatar">
	</a>
	</div>
	</div>*@

	<!-- Navbar on small screens -->
	<div id="navDemo" class="w3-bar-block w3-theme-d2 w3-hide w3-hide-large w3-hide-medium w3-large">
		<a asp-controller="EasyQuiz" asp-action="Privacy" class="w3-bar-item w3-button w3-padding-large">EasyQuiz</a>
		<a asp-controller="Home" asp-action="Index" class="w3-bar-item w3-button w3-padding-large">Home</a>
		<a asp-controller="Home" asp-action="Profile" class="w3-bar-item w3-button w3-padding-large">My Profile</a>
		<a asp-controller="Score" asp-action="Result" class="w3-bar-item w3-button w3-padding-large">Score Report</a>
		<a asp-action="Logout" asp-controller="Account" class="w3-bar-item w3-button w3-padding-large">Sign out</a>
	</div>

	@RenderBody()

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="https://webrtc.github.io/adapter/adapter-latest.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="~/lib/bootstrap/js/bootstrap.js"></script>
	<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>

	@*<script type="text/javascript" src="~/lib/bootstrap/dist/js/bootstrap.js"></script>*@
	<script type="text/javascript" src="~/vendor/bootstrap/js/popper.js"></script>	

	<environment include="Development">
		<script src="~/js/site.js" asp-append-version="true"></script>
	</environment>
	<environment exclude="Development">
		<script src="~/js/site.min.js" asp-append-version="true"></script>
	</environment>

	<script type="text/javascript">
		// Accordion
		function myFunction(id) {
			var x = document.getElementById(id);
			if (x.className.indexOf("w3-show") == -1) {
				x.className += " w3-show";
				x.previousElementSibling.className += " w3-theme-d1";
			} else {
				x.className = x.className.replace("w3-show", "");
				x.previousElementSibling.className =
					x.previousElementSibling.className.replace(" w3-theme-d1", "");
			}
		}

		// Used to toggle the menu on smaller screens when clicking on the menu button
		function openNav() {
			var x = document.getElementById("navDemo");
			if (x.className.indexOf("w3-show") == -1) {
				x.className += " w3-show";
			} else {
				x.className = x.className.replace(" w3-show", "");
			}
		}
	</script>
	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>